#!/usr/bin/python

# Copyright (c) 2012 Oliver Burger obgr_seneca@mageia.org
#
# This file is part of videoconvert.
#
# videoconvert is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# videoconvert is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with videoconvert.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

# self written imports
import videoconvert.Conf as Conf
import videoconvert.SystemCall as SystemCall

# check if the --config option is given
commandCall = sys.argv.pop(0)
arguments = sys.argv
conf = Conf.Configuration()
confFile = conf.getConfFile()

# if no config file exists or --config is given ask the user for his preffered settings
# otherwise read the config file
if ((os.path.exists(confFile) == False) or (len(arguments) >= 1 and arguments[0] == '--config')):
    arguments.pop(0)
    conf.getNewConfig()
else:
    conf.readConfig()

# read the remaining arguments from the command line
if len(arguments) >= 1:
    if os.path.isdir(arguments[0]):
        inDir = arguments.pop(0)
        inFile = ''
    else:
        inFile = arguments.pop(0)
        inDir = ''
    if len(arguments) >= 1:
        name = arguments.pop(0)
    else:
        name = 'videoconvert'

    # if a directory is given try to sync vdr files in that directory and convert them
    # if a file is given only convert it
    systemCall = SystemCall.SystemCall(conf)
    if inDir != '':
        systemCall.sync(inDir,name)
    elif inFile != '':
        systemCall.convertFile(inFile,os.getcwd(),os.getcwd())

else:
    print 'Usage : '+commandCall+' [--config] <input directory> [<name>]'

#print conf.toString()
